# Creating the Dataset

## Imports

In [1]:
import snscrape.modules.twitter as sntwitter
import pandas as pd
import numpy as np
import time

## Webscraping the Democratic Party's Tweets

In [2]:
%%time
bidenl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:JoeBiden since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    bidenl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems1 = pd.DataFrame(bidenl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems1

CPU times: user 7.63 s, sys: 456 ms, total: 8.09 s
Wall time: 2min 26s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:55:03+00:00,1587443101790048258,One more week until Election Day. \n\nLet’s do...,JoeBiden
1,2022-11-01 01:27:00+00:00,1587254848940085253,Democrats will protect Social Security.\nWe’ll...,JoeBiden
2,2022-10-31 22:30:02+00:00,1587210314663215105,"With Election Day right around the corner, I’m...",JoeBiden
3,2022-10-31 20:29:01+00:00,1587179858236305408,I know which side I’m on.\nhttps://t.co/RBiVHJ...,JoeBiden
4,2022-10-31 18:22:05+00:00,1587147915050500103,Make your plan to vote early or on Election Da...,JoeBiden
...,...,...,...,...
6250,2017-02-06 01:29:42+00:00,828415338886942721,Incredible performance from my friend @LadyGag...,JoeBiden
6251,2017-02-02 22:33:55+00:00,827283937000951808,Our tolerance and diversity make America great...,JoeBiden
6252,2017-02-01 16:25:37+00:00,826828864009678850,From fighting cancer to changing the culture o...,JoeBiden
6253,2017-02-01 14:57:38+00:00,826806724006965248,We cannot yield an inch on all the progress we...,JoeBiden
6254,2017-02-01 14:57:19+00:00,826806641370791936,"Now more than ever, we must work hard to prese...",JoeBiden

In [3]:
%%time
bidenl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:POTUS since:2021-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    bidenl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems2 = pd.DataFrame(bidenl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems2

CPU times: user 4.79 s, sys: 294 ms, total: 5.08 s
Wall time: 1min 24s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:30:25+00:00,1587436902122196995,It’s time for oil companies to stop the war pr...,POTUS
1,2022-11-01 01:45:02+00:00,1587259387525177346,Happy Halloween! https://t.co/zsNvQPDCs3,POTUS
2,2022-11-01 01:27:28+00:00,1587254966309240841,"In the last six months, 6 of the largest oil c...",POTUS
3,2022-10-31 22:00:01+00:00,1587202758515499010,Gas prices are down more than $1.20 since thei...,POTUS
4,2022-10-31 21:05:51+00:00,1587189129271562241,The oil industry has a choice.\n\nEither inves...,POTUS
...,...,...,...,...
4182,2021-01-21 02:25:00+00:00,1352079719945162752,I applaud the Senate for putting partisanship ...,POTUS
4183,2021-01-21 01:57:34+00:00,1352072818847068163,We're back in the Paris Climate Agreement.,POTUS
4184,2021-01-20 23:03:55+00:00,1352029117974278145,After taking the oath of office this afternoon...,POTUS
4185,2021-01-20 18:31:00+00:00,1351960433905700864,The time to move forward is now. https://t.co/...,POTUS
4186,2021-01-20 17:36:59+00:00,1351946842838347776,There is no time to waste when it comes to tac...,POTUS

In [4]:
%%time
sandersl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:BernieSanders since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    sandersl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems3 = pd.DataFrame(sandersl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems3

CPU times: user 9.85 s, sys: 550 ms, total: 10.4 s
Wall time: 3min 14s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:10:24+00:00,1587462065899425793,RSVP to join us in Eau Claire: https://t.co/UQ...,BernieSanders
1,2022-11-01 15:10:23+00:00,1587462060350357504,"This weekend, I am headed to Wisconsin to rall...",BernieSanders
2,2022-10-31 19:59:53+00:00,1587172529789091841,No. I will apologize to no one for helping to ...,BernieSanders
3,2022-10-31 16:05:00+00:00,1587113417063759878,Medicare for All. Tuition-free higher educatio...,BernieSanders
4,2022-10-30 23:33:46+00:00,1586863963283009536,"The people of Brazil have voted for democracy,...",BernieSanders
...,...,...,...,...
8050,2017-01-22 16:50:01+00:00,823211123960872962,President Trump: Women aren’t going back to se...,BernieSanders
8051,2017-01-21 16:18:55+00:00,822840912434831360,We won't achieve our goals if we treat democra...,BernieSanders
8052,2017-01-21 00:39:01+00:00,822604378142081027,We must vigorously defend DACA and the young p...,BernieSanders
8053,2017-01-20 15:23:12+00:00,822464499718520836,Our response to Mr. Trump's inauguration has t...,BernieSanders
8054,2017-01-20 02:17:51+00:00,822266860716617730,There should be no disagreement that the First...,BernieSanders

In [5]:
%%time
sandersl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenSanders since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    sandersl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems4 = pd.DataFrame(sandersl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems4

CPU times: user 7.42 s, sys: 409 ms, total: 7.83 s
Wall time: 2min 28s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 17:18:46+00:00,1587131980637954048,President Biden is right. At a time when Exxon...,SenSanders
1,2022-10-30 23:31:23+00:00,1586863364743073792,"Today, the people of Brazil have voted for dem...",SenSanders
2,2022-10-28 19:46:55+00:00,1586082101454962688,Profits in last 2 quarters\nExxon:⬆️228% to $3...,SenSanders
3,2022-10-28 18:19:57+00:00,1586060216356962307,Many international studies point to Finland as...,SenSanders
4,2022-10-28 16:53:57+00:00,1586038572334960640,I wish Paul Pelosi a quick recovery from this ...,SenSanders
...,...,...,...,...
6047,2017-01-21 00:18:01+00:00,822599091834208257,"At a time of massive attacks on privacy, I wil...",SenSanders
6048,2017-01-21 00:09:12+00:00,822596873135525888,We must not stop vigorously defending DACA and...,SenSanders
6049,2017-01-20 23:58:13+00:00,822594111240814592,In a cabinet loaded with extremists I hope Gen...,SenSanders
6050,2017-01-20 15:06:02+00:00,822460180432420866,"Today will be a tough day, but we can't throw ...",SenSanders
6051,2017-01-20 14:26:10+00:00,822450149997891585,The entire First Family represented our countr...,SenSanders

In [6]:
%%time
pelosil1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SpeakerPelosi since:2019-01-03 lang:en').get_items()):
    if i == maxTweets:
        break
    pelosil1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems5 = pd.DataFrame(pelosil1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems5

CPU times: user 5.98 s, sys: 334 ms, total: 6.31 s
Wall time: 1min 50s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 00:35:09+00:00,1587241802431860736,Since the horrific attack on Paul early Friday...,SpeakerPelosi
1,2022-10-30 01:30:59+00:00,1586531076192993280,Read my letter to my colleagues in the Congres...,SpeakerPelosi
2,2022-10-30 01:30:59+00:00,1586531074511089664,Please know that the prayers and warm wishes f...,SpeakerPelosi
3,2022-10-27 22:08:18+00:00,1585755291316113411,"This week, I was proud to represent the Congre...",SpeakerPelosi
4,2022-10-27 15:10:06+00:00,1585650050734120960,"Through that vital work, we strive to console ...",SpeakerPelosi
...,...,...,...,...
4908,2019-01-03 20:05:11+00:00,1080918011366834176,Guided by the vision and values of our Founder...,SpeakerPelosi
4909,2019-01-03 19:54:48+00:00,1080915398873284608,The middle class is the backbone of our democr...,SpeakerPelosi
4910,2019-01-03 19:48:12+00:00,1080913740177068032,We have heard from too many families who wonde...,SpeakerPelosi
4911,2019-01-03 17:03:04+00:00,1080872181666664448,As the House of Representatives opens the 116t...,SpeakerPelosi
4912,2019-01-03 00:02:02+00:00,1080615229678125057,During today’s meeting between @realDonaldTrum...,SpeakerPelosi

In [7]:
%%time
pelosil2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:TeamPelosi since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    pelosil2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems6 = pd.DataFrame(pelosil2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems6

CPU times: user 6.09 s, sys: 346 ms, total: 6.44 s
Wall time: 2min 10s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 21:25:00+00:00,1587193946861469697,Social Security is your money. Democrats hear ...,TeamPelosi
1,2022-10-31 16:30:22+00:00,1587119801666879488,We all have a role to play in defending our De...,TeamPelosi
2,2022-10-30 01:20:00+00:00,1586528311102013440,Thank you for your prayers for my husband and ...,TeamPelosi
3,2022-10-28 01:30:05+00:00,1585806075714060288,As we celebrate 50 years of the Golden Gate Na...,TeamPelosi
4,2022-10-27 21:00:29+00:00,1585738225233993728,When Democrats put up a plan to stop profitabl...,TeamPelosi
...,...,...,...,...
5040,2017-01-21 23:30:03+00:00,822949407666696192,Yesterday was for Trump's rhetoric. Today is f...,TeamPelosi
5041,2017-01-21 19:37:54+00:00,822890986879811584,Thank you #WomensMarch organizers for galvaniz...,TeamPelosi
5042,2017-01-21 17:48:06+00:00,822863355631300610,Nancy and the team are marching today in the @...,TeamPelosi
5043,2017-01-20 23:28:45+00:00,822586693987528705,RT if you'll join the fight to #ProtectOurCare...,TeamPelosi
5044,2017-01-20 17:46:24+00:00,822500541100130304,RT to thank President Obama for 8 years of pro...,TeamPelosi

In [8]:
%%time
schumerl1 = []
maxTweets = 20000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenSchumer since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    schumerl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems7 = pd.DataFrame(schumerl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems7

CPU times: user 12 s, sys: 698 ms, total: 12.7 s
Wall time: 4min 16s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 22:15:34+00:00,1587206672933691392,Trick-or-treating with Mickey and Minnie! http...,SenSchumer
1,2022-10-31 20:15:01+00:00,1587176336786866177,Big Oil is raking in profits.\n\nRepublicans w...,SenSchumer
2,2022-10-29 19:15:10+00:00,1586436499247353857,Donald Trump’s lies about the 2020 election co...,SenSchumer
3,2022-10-29 13:56:49+00:00,1586356384777441280,10 years ago—Superstorm Sandy hit NY.\n\nSince...,SenSchumer
4,2022-10-28 20:50:52+00:00,1586098194689073152,Exxon and Big Oil have gleefully raked in prof...,SenSchumer
...,...,...,...,...
10149,2017-01-22 13:22:22+00:00,823158869761343488,Tune in this morning: https://t.co/8IaqrhfL3t,SenSchumer
10150,2017-01-20 22:52:21+00:00,822577533845704706,It only took an hour for those populist words ...,SenSchumer
10151,2017-01-20 22:20:09+00:00,822569430672666624,Telling &amp; troubling that the Trump Adminis...,SenSchumer
10152,2017-01-20 00:44:30+00:00,822243371561447424,"Barrett was a brilliant NY beacon, cleaning up...",SenSchumer
10153,2017-01-20 00:40:56+00:00,822242471883243520,"If heaven has a flaw, we're gonna find out soo...",SenSchumer

In [9]:
%%time
schumerl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:chuckschumer since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    schumerl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems8 = pd.DataFrame(schumerl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems8

CPU times: user 761 ms, sys: 37.8 ms, total: 798 ms
Wall time: 14.2 s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:18:51+00:00,1587464191128002560,One week left until one of the most important ...,chuckschumer
1,2022-10-30 23:01:00+00:00,1586855718493331459,I’m so proud of all we’ve done to deliver for ...,chuckschumer
2,2022-10-29 20:35:04+00:00,1586456606895546368,📅Early Voting in New York begins TODAY!\n\n🗳Do...,chuckschumer
3,2022-10-28 20:39:20+00:00,1586095292273033218,The Working Families Party is a champion for w...,chuckschumer
4,2022-10-25 23:00:02+00:00,1585043534767620097,.@KathyHochul has been a strong leader for New...,chuckschumer
...,...,...,...,...
508,2017-05-12 17:46:02+00:00,863087888875085824,Congrats to new @DNC CEO @JessOConne11. I look...,chuckschumer
509,2017-04-12 02:29:04+00:00,851985491264237568,.@TheDemocrats fight in Kansas is just the sta...,chuckschumer
510,2017-02-25 21:38:49+00:00,835604993457733632,Congrats also to @keithellison &amp; @EllisonC...,chuckschumer
511,2017-02-25 21:36:12+00:00,835604333718867968,Hard fought #DNCChair race. Congrats to the ne...,chuckschumer
512,2017-02-25 14:18:01+00:00,835494062862008320,Yes it would! https://t.co/khuOGNWH6o,chuckschumer

In [10]:
%%time
harrisl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:VP since:2021-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    harrisl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems9 = pd.DataFrame(harrisl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems9

CPU times: user 2.31 s, sys: 148 ms, total: 2.45 s
Wall time: 11min 17s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 23:44:30+00:00,1587229053408481280,Happy Halloween! https://t.co/vTcnR6zcEp,VP
1,2022-10-31 20:55:38+00:00,1587186559673110529,We stand with the people of India who are mour...,VP
2,2022-10-31 13:35:00+00:00,1587075668910739465,Here’s what we’ve done so far:\n— provided rel...,VP
3,2022-10-29 23:15:00+00:00,1586496856393220096,Doug and I send our condolences to those griev...,VP
4,2022-10-29 17:41:00+00:00,1586412801698009090,"If you know a teacher, health care worker, or ...",VP
...,...,...,...,...
1966,2021-01-21 15:17:19+00:00,1352274079051620360,I stand on the shoulders of those who came bef...,VP
1967,2021-01-21 03:21:44+00:00,1352093996227637249,This moment embodies our character as a nation...,VP
1968,2021-01-21 00:56:49+00:00,1352057526641172483,It was an honor to return to the Senate to swe...,VP
1969,2021-01-20 18:11:22+00:00,1351955494978646018,It's an honor to be your Vice President. https...,VP
1970,2021-01-20 17:02:10+00:00,1351938078643003393,Ready to serve.,VP

In [11]:
%%time
harrisl2 = []
maxTweets = 20000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:KamalaHarris since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    harrisl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems10 = pd.DataFrame(harrisl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems10

CPU times: user 11.7 s, sys: 789 ms, total: 12.5 s
Wall time: 4min 32s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 14:39:00+00:00,1587454163612475392,"One week from today, Americans across the coun...",KamalaHarris
1,2022-10-30 22:03:25+00:00,1586841229643612160,You have the power to stop Republican-led atta...,KamalaHarris
2,2022-10-30 17:21:00+00:00,1586770156277178368,"Election Day is right around the corner, so we...",KamalaHarris
3,2022-10-30 16:38:00+00:00,1586759334993739776,Make your voice heard at the ballot box by mak...,KamalaHarris
4,2022-10-29 18:14:00+00:00,1586421106566651905,10 days left until Election Day. That’s 10 day...,KamalaHarris
...,...,...,...,...
10823,2017-01-20 16:09:26+00:00,822476135057526784,So here’s the deal: our ideals are at stake ri...,KamalaHarris
10824,2017-01-20 14:53:00+00:00,822456900910546945,We must not despair. We must not be overwhelme...,KamalaHarris
10825,2017-01-20 14:02:30+00:00,822444194321092608,We must not remain silent in a time that requi...,KamalaHarris
10826,2017-01-20 01:52:58+00:00,822260600118120449,The GOP’s attacks on @PPact &amp; women’s acce...,KamalaHarris
10827,2017-01-20 00:01:11+00:00,822232466786283521,Let us all stand up for people who deserve to ...,KamalaHarris

In [12]:
%%time
warrenl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenWarren since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    warrenl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems11 = pd.DataFrame(warrenl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems11

CPU times: user 8.1 s, sys: 551 ms, total: 8.65 s
Wall time: 3min 2s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:59:06+00:00,1587444121194594304,Leading healthcare providers reveal in my new ...,SenWarren
1,2022-11-01 00:16:50+00:00,1587237191293468673,Blocking the @penguinrandom merger with @simon...,SenWarren
2,2022-10-31 21:17:58+00:00,1587192177058275328,Big Oil companies' record profits are a windfa...,SenWarren
3,2022-10-31 17:30:24+00:00,1587134907561791488,❗ ATTENTION public servants ❗️\n\nToday is the...,SenWarren
4,2022-10-31 13:54:06+00:00,1587080477340565504,"After 30 years of tax cuts, billionaire corpor...",SenWarren
...,...,...,...,...
7229,2017-01-23 21:11:27+00:00,823639306543710209,Attacking @PPFA &amp; US women’s reproductive ...,SenWarren
7230,2017-01-20 23:27:23+00:00,822586351744847873,We must measure @POTUS @realDonaldTrump by act...,SenWarren
7231,2017-01-20 23:26:15+00:00,822586064246370308,"That’s 40,000 families who just lost their cha...",SenWarren
7232,2017-01-20 23:25:30+00:00,822585874718330881,.@POTUS suspended a planned cut in FHA mortgag...,SenWarren
7233,2017-01-20 23:24:21+00:00,822585584942202882,"Just minutes after taking the oath of office, ...",SenWarren

In [13]:
%%time
warrenl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:ewarren since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    warrenl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems12 = pd.DataFrame(warrenl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems12

CPU times: user 10.8 s, sys: 707 ms, total: 11.5 s
Wall time: 4min 5s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:48:55+00:00,1587441560215429120,"At least 10,000 decisions that the government ...",ewarren
1,2022-10-31 23:48:03+00:00,1587229947885764608,Bailey and I wish you a safe and happy Hallowe...,ewarren
2,2022-10-31 21:47:22+00:00,1587199575193968644,"Thank you, President @BarackObama, for making ...",ewarren
3,2022-10-31 18:08:35+00:00,1587144516489936897,Big Oil is gouging working people at the pump ...,ewarren
4,2022-10-31 14:10:17+00:00,1587084548369702913,Today’s the last day to apply for student debt...,ewarren
...,...,...,...,...
9566,2017-02-04 19:57:51+00:00,827969435927453696,"Our country is in crisis because for years, Wa...",ewarren
9567,2017-02-04 19:56:34+00:00,827969112710184966,Our country is in crisis – but that crisis did...,ewarren
9568,2017-01-23 02:47:06+00:00,823361387808354304,Woo-hoo! Let's go Pats! #Patriots,ewarren
9569,2017-01-21 20:29:31+00:00,822903977570340868,Happy to march with 125k+ women (&amp; friends...,ewarren
9570,2017-01-20 14:39:50+00:00,822453588572176386,"Thank you, President @BarackObama. We'll miss ...",ewarren

In [14]:
%%time
aocl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:AOC since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    aocl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems13 = pd.DataFrame(aocl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems13

CPU times: user 10.7 s, sys: 587 ms, total: 11.3 s
Wall time: 3min 55s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 21:19:45+00:00,1587192628038307840,"Shamefully, AIPAC is working for Republican co...",AOC
1,2022-10-31 18:23:13+00:00,1587148199265026057,Proud to represent one of the safest places in...,AOC
2,2022-10-31 02:39:12+00:00,1586910629729804288,Notice how Republicans are frothing at the mou...,AOC
3,2022-10-29 20:23:39+00:00,1586453732057047040,Happy Halloween from Olaf and Sriracha at Cast...,AOC
4,2022-10-29 13:26:03+00:00,1586348640435855360,@pdabrosca “Sanders denounced the shooting ram...,AOC
...,...,...,...,...
8346,2017-05-17 12:26:40+00:00,864819456069042176,It's official: we're running for NY-14! Thank ...,AOC
8347,2017-05-17 12:11:38+00:00,864815671288442881,@staceyhopkinsga @BrandNew535 @robb2018 @AdrBe...,AOC
8348,2017-05-16 21:13:11+00:00,864589569823518720,Thank you Lyel - motivated by so many people r...,AOC
8349,2017-05-16 16:14:07+00:00,864514309564616704,Looking forward to this! New @BrandNew535 cand...,AOC
8350,2017-05-09 00:54:36+00:00,861746190228086784,Thank you for having me! It's a dream to speak...,AOC

In [15]:
%%time
aocl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepAOC since:2019-01-03 lang:en').get_items()):
    if i == maxTweets:
        break
    aocl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems14 = pd.DataFrame(aocl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems14

CPU times: user 1.41 s, sys: 83.2 ms, total: 1.5 s
Wall time: 28.2 s

,Date,Tweet ID,Tweet,Username
0,2022-10-27 19:46:01+00:00,1585719485516115968,Thank you @HispanicCaucus for supporting the I...,RepAOC
1,2022-10-26 17:03:03+00:00,1585316088887201792,A federal appeals court has temporarily halted...,RepAOC
2,2022-10-24 14:35:57+00:00,1584554293558120448,Happy Diwali to everyone celebrating in NY-14 ...,RepAOC
3,2022-10-20 13:37:00+00:00,1583089904531144705,As red states continue to ban books from schoo...,RepAOC
4,2022-10-18 20:32:04+00:00,1582469585680289792,Have you heard of the updated COVID-19 booster...,RepAOC
...,...,...,...,...
1071,2019-01-14 20:48:28+00:00,1084915172504989696,"I’ve been getting letters, visits, &amp; calls...",RepAOC
1072,2019-01-13 02:38:43+00:00,1084278540596662272,"It is a complete injustice that to this day, s...",RepAOC
1073,2019-01-13 02:36:00+00:00,1084277855016706049,Thank you @townhallproject! https://t.co/BjGxf...,RepAOC
1074,2019-01-09 18:03:38+00:00,1083061753322397698,It was an honor of a lifetime to meet with Rev...,RepAOC
1075,2019-01-08 18:30:41+00:00,1082706172623376384,I just had a furloughed worker come visit me i...,RepAOC

In [16]:
%%time
watersl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepMaxineWaters since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    watersl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems15 = pd.DataFrame(watersl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems15

CPU times: user 1.32 s, sys: 79.5 ms, total: 1.4 s
Wall time: 22.8 s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 21:42:04+00:00,1587198241229180929,Halloween is meant to be a fun time! Mimicking...,RepMaxineWaters
1,2022-10-31 17:18:16+00:00,1587131854469095430,So happy to hear that Paul Pelosi is recoverin...,RepMaxineWaters
2,2022-10-28 21:51:58+00:00,1586113570668175360,"My friend, Roz Wyman was a highly respected De...",RepMaxineWaters
3,2022-10-25 21:43:08+00:00,1585024184866189312,Clarence Thomas has abused his powers to freez...,RepMaxineWaters
4,2022-10-21 22:45:38+00:00,1583590359963090944,The Jan 6th Committee is serious about documen...,RepMaxineWaters
...,...,...,...,...
1091,2017-01-23 16:18:49+00:00,823565660945088512,Nominee Betsy DeVos’s Knowledge of Education B...,RepMaxineWaters
1092,2017-01-21 21:12:12+00:00,822914716662165504,I was so proud to see my friend @GloriaSteinem...,RepMaxineWaters
1093,2017-01-21 15:34:29+00:00,822829729795473409,I'll be joining @JoyAnnReid this morning at 10...,RepMaxineWaters
1094,2017-01-21 14:25:27+00:00,822812355704881152,I'll be joining @npratc today at 5:00 pm w/ @N...,RepMaxineWaters
1095,2017-01-20 04:30:29+00:00,822300240262795265,"Maxine Waters on ""TMZ Live"" -- https://t.co/u9...",RepMaxineWaters

In [17]:
%%time
watersl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:MaxineWaters since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    watersl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems16 = pd.DataFrame(watersl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems16

CPU times: user 1.45 s, sys: 84.2 ms, total: 1.53 s
Wall time: 26.5 s

,Date,Tweet ID,Tweet,Username
0,2022-02-11 16:19:39+00:00,1492171484902539272,"Rep. Hmm Rogers apologizing after ""Kiss my a**...",MaxineWaters
1,2021-06-29 14:19:07+00:00,1409879103629664264,".@ToneStith, you don’t need a do over! Auntie ...",MaxineWaters
2,2021-06-19 18:01:11+00:00,1406311112828755969,Come now! We are here until 2pm at Crozier Mid...,MaxineWaters
3,2021-06-19 15:57:36+00:00,1406280011791933442,I’m celebrating #Juneteenth by doing a big foo...,MaxineWaters
4,2020-12-11 20:18:17+00:00,1337491917144207363,ICYMI: Sidelined from protests after an injury...,MaxineWaters
...,...,...,...,...
1143,2017-08-11 17:11:41+00:00,896056538762100738,@AlexMohajer @HillaryClinton @MaxineWaters @an...,MaxineWaters
1144,2017-04-17 19:26:50+00:00,854053558186102784,I will not get distracted and I won't stop fig...,MaxineWaters
1145,2017-04-17 19:20:40+00:00,854052004951445504,Do not be distracted by this President. Stay ...,MaxineWaters
1146,2017-04-17 19:19:04+00:00,854051604164730882,I was so thrilled to participate in the #taxma...,MaxineWaters
1147,2017-04-12 22:36:01+00:00,852289229572931585,"Join ""Auntie Maxine"" at @busboysandpoets (5th ...",MaxineWaters

In [18]:
%%time
bookerl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:CoryBooker since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    bookerl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems17 = pd.DataFrame(bookerl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems17

CPU times: user 8.28 s, sys: 451 ms, total: 8.73 s
Wall time: 2min 52s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 19:04:42+00:00,1587158640145874945,New Jersey – for the first time ever in a midt...,CoryBooker
1,2022-10-31 11:49:47+00:00,1587049189116108802,"And yes, this is my 9th anniversary of being s...",CoryBooker
2,2022-10-31 11:49:46+00:00,1587049185236451331,Halloween is the perfect excuse to share some ...,CoryBooker
3,2022-10-30 17:47:27+00:00,1586776811517710338,"""Interdependence is and ought to be as much th...",CoryBooker
4,2022-10-29 11:40:35+00:00,1586322101044060160,My 300th daily run in a row. https://t.co/zTVf...,CoryBooker
...,...,...,...,...
6616,2017-01-23 15:00:16+00:00,823545893278326784,Trump Administration is calling for the elimin...,CoryBooker
6617,2017-01-23 13:50:19+00:00,823528292393320449,"""Nothing strengthens authority so much as sile...",CoryBooker
6618,2017-01-21 14:28:35+00:00,822813143210557441,Proud to stand with @CecileRichards &amp; Plan...,CoryBooker
6619,2017-01-21 13:03:38+00:00,822791766562787329,"""No person is your friend who demands your sil...",CoryBooker
6620,2017-01-20 13:20:31+00:00,822433627095109633,"This is not a time to curl up, give up or shut...",CoryBooker

In [19]:
%%time
bookerl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenBooker since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    bookerl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems18 = pd.DataFrame(bookerl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems18

CPU times: user 4.46 s, sys: 247 ms, total: 4.71 s
Wall time: 1min 27s

,Date,Tweet ID,Tweet,Username
0,2022-10-28 16:40:55+00:00,1586035294444597248,"Today I joined @GovMurphy, @SenatorMenendez, @...",SenBooker
1,2022-10-28 15:40:51+00:00,1586020176566571009,I'm profoundly disturbed to hear Speaker Pelos...,SenBooker
2,2022-10-27 18:40:09+00:00,1585702912008888322,"Today, we remember the lives of 11 Jewish comm...",SenBooker
3,2022-10-27 14:42:29+00:00,1585643098314457089,Federal judges should not live in fear that th...,SenBooker
4,2022-10-27 14:06:16+00:00,1585633987057176579,This is great news from @HHSGov ahead of open ...,SenBooker
...,...,...,...,...
3503,2017-01-23 23:37:22+00:00,823676026802831362,Today @CoryBooker met with NJ women’s rights a...,SenBooker
3504,2017-01-20 22:21:01+00:00,822569649481125888,Trump Admin. is calling for the elimination of...,SenBooker
3505,2017-01-20 22:10:25+00:00,822566982486814720,President Obama signs final bill—bipartisan le...,SenBooker
3506,2017-01-20 21:23:42+00:00,822555226486046721,First 2 petitions on https://t.co/MAb1WWYeRs a...,SenBooker
3507,2017-01-20 04:21:01+00:00,822297856602152961,"Climate change is not only real, it is a dange...",SenBooker

In [20]:
%%time
jayapall1 = []
maxTweets = 20000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepJayapal since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    jayapall1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems19 = pd.DataFrame(jayapall1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems19

CPU times: user 22.4 s, sys: 1.14 s, total: 23.6 s
Wall time: 7min 53s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 14:30:00+00:00,1587451897987858433,⚠Election Day is one week away⚠\n\nMake a plan...,RepJayapal
1,2022-10-31 21:30:00+00:00,1587195206868213760,Don't miss your chance! The PSLF waiver closes...,RepJayapal
2,2022-10-31 17:15:00+00:00,1587131033094393858,Democrats are working to lower costs and raise...,RepJayapal
3,2022-10-31 15:00:02+00:00,1587097066391609346,The Inflation Reduction Act will:\n\n💡 Cut ene...,RepJayapal
4,2022-10-31 04:39:20+00:00,1586940863527407617,Lula winning is a huge and hopeful sign for ou...,RepJayapal
...,...,...,...,...
17925,2017-01-20 16:55:38+00:00,822487764155281410,"""This is not a normal time and we cannot prete...",RepJayapal
17926,2017-01-20 16:40:53+00:00,822484051244163072,Wondering why I'm with the people of my distri...,RepJayapal
17927,2017-01-20 02:19:20+00:00,822267236396085248,This is my message to all the people who are t...,RepJayapal
17928,2017-01-20 01:19:31+00:00,822252183538147328,My interview with @KUOW: Here's why Congresswo...,RepJayapal
17929,2017-01-20 01:03:58+00:00,822248267853352960,Positive conversation with @downtownseattle to...,RepJayapal

In [21]:
%%time
jayapall2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:PramilaJayapal since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    jayapall2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems20 = pd.DataFrame(jayapall2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems20

CPU times: user 7.93 s, sys: 399 ms, total: 8.33 s
Wall time: 2min 46s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:16:02+00:00,1587463481930006530,"If the Republicans control Congress, they’ll t...",PramilaJayapal
1,2022-11-01 01:39:00+00:00,1587257869224890368,You know what scares me the most this Hallowee...,PramilaJayapal
2,2022-10-31 23:38:00+00:00,1587227418615549954,Tonight is our FINAL fundraising deadline befo...,PramilaJayapal
3,2022-10-31 21:22:00+00:00,1587193193837350912,Washingtonians — if you aren’t already registe...,PramilaJayapal
4,2022-10-31 18:25:01+00:00,1587148653973512192,Big Oil is expected to report a $50B profit fr...,PramilaJayapal
...,...,...,...,...
6412,2017-01-20 14:59:24+00:00,822458511439302656,I was able to live my American dream for one s...,PramilaJayapal
6413,2017-01-20 14:57:09+00:00,822457946877599744,I emigrated to the US from India at 16. My par...,PramilaJayapal
6414,2017-01-20 04:33:20+00:00,822300959367757824,Had a great conversation with @KUOW about why ...,PramilaJayapal
6415,2017-01-20 04:00:19+00:00,822292648270512129,Great interview with @BrandiKruse on why I am ...,PramilaJayapal
6416,2017-01-20 00:31:24+00:00,822240072951013376,A very powerful read about the stories of our ...,PramilaJayapal

In [22]:
%%time
klobucharl1 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:amyklobuchar since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    klobucharl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems21 = pd.DataFrame(klobucharl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems21

CPU times: user 12.4 s, sys: 621 ms, total: 13 s
Wall time: 4min 7s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 04:40:58+00:00,1587303661704605699,Best Halloween moon ever! (Taken from airplane...,amyklobuchar
1,2022-11-01 02:49:15+00:00,1587275548044263424,"If anyone has Nevada's back, it's Catherine @C...",amyklobuchar
2,2022-11-01 01:38:07+00:00,1587257648314982400,Catherine @CortezMasto can count on her alma m...,amyklobuchar
3,2022-10-31 20:15:12+00:00,1587176382060191748,More than 20 MILLION Americans have already vo...,amyklobuchar
4,2022-10-31 17:42:30+00:00,1587137952206970886,Great news! The Smithsonian just recommended t...,amyklobuchar
...,...,...,...,...
9790,2017-01-21 19:47:04+00:00,822893294178959361,Here I am with our Minnesota group...some hear...,amyklobuchar
9791,2017-01-21 15:34:46+00:00,822829799689351170,Speaking to our MN marchers in DC at the #Wome...,amyklobuchar
9792,2017-01-21 14:02:21+00:00,822806542227476481,Peaceful transition of power yesterday. Peace...,amyklobuchar
9793,2017-01-20 17:32:19+00:00,822496994249867268,A bit of camaraderie...my seat mates at the in...,amyklobuchar
9794,2017-01-20 04:54:58+00:00,822306400130871299,Questcor settlement sends a strong message: We...,amyklobuchar

In [23]:
%%time
klobucharl2 = []
maxTweets = 10000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenAmyKlobuchar since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    klobucharl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems22 = pd.DataFrame(klobucharl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems22

CPU times: user 2.07 s, sys: 115 ms, total: 2.18 s
Wall time: 42.5 s

,Date,Tweet ID,Tweet,Username
0,2022-10-28 00:27:03+00:00,1585790209916305408,Medicare Open Enrollment has begun. If you’re ...,SenAmyKlobuchar
1,2022-10-26 21:10:42+00:00,1585378412017094657,I hope everyone gets a chance to enjoy the fal...,SenAmyKlobuchar
2,2022-10-26 02:35:19+00:00,1585097713783541762,It's hard to believe that it's been 20 years s...,SenAmyKlobuchar
3,2022-10-18 23:53:21+00:00,1582520239157563393,"During Breast Cancer Awareness Month, I hope m...",SenAmyKlobuchar
4,2022-10-16 20:03:47+00:00,1581737689526595584,So great to see Rochester recognized as one of...,SenAmyKlobuchar
...,...,...,...,...
1597,2018-02-07 22:08:24+00:00,961361025688834048,"On the Senate floor today, Senator Klobuchar s...",SenAmyKlobuchar
1598,2018-01-25 00:01:31+00:00,956316064614420480,"The Super Bowl is just over a week away, which...",SenAmyKlobuchar
1599,2018-01-12 02:31:23+00:00,951642736515538945,A bipartisan group of Senators announced they ...,SenAmyKlobuchar
1600,2018-01-09 18:24:36+00:00,950795458062028801,Today Senator Klobuchar joined @SenMarkey and ...,SenAmyKlobuchar
1601,2018-01-09 18:03:22+00:00,950790112719368192,"The @FCC may have voted to end #NetNeutrality,...",SenAmyKlobuchar

In [24]:
%%time
demsl1 = []
maxTweets = 20000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:TheDemocrats since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    demsl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
dems23 = pd.DataFrame(demsl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

dems23

CPU times: user 17.4 s, sys: 888 ms, total: 18.2 s
Wall time: 5min 45s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:30:07+00:00,1587467028243386374,Election Day is in one week. Visit https://t.c...,TheDemocrats
1,2022-11-01 14:05:04+00:00,1587445621178474499,"This Native American Heritage Month, we recogn...",TheDemocrats
2,2022-11-01 01:29:00+00:00,1587255352810160128,This is the choice this November.\nhttps://t.c...,TheDemocrats
3,2022-11-01 00:19:01+00:00,1587237741665869827,"Michigan, early voting is happening! Make your...",TheDemocrats
4,2022-10-31 22:35:00+00:00,1587211564612030464,"👻 Don't boo, vote. Find out if you're eligible...",TheDemocrats
...,...,...,...,...
14337,2017-01-21 13:44:43+00:00,822802106788835328,If you're worried you'll be discriminated agai...,TheDemocrats
14338,2017-01-20 18:09:38+00:00,822506385984417799,Thank you. https://t.co/EUCIUgyTm6,TheDemocrats
14339,2017-01-20 17:56:37+00:00,822503110274859008,Thank you. https://t.co/4wfRsM3BWt,TheDemocrats
14340,2017-01-20 17:00:45+00:00,822489051932594176,We’re here and we’re ready to fight back. Say ...,TheDemocrats
14341,2017-01-20 14:48:44+00:00,822455827181305858,There’s only one thing left to say after eight...,TheDemocrats

## Creating the Democratic Party Tweet Dataframe

In [124]:
pdList1 = [dems1, dems2, dems3, dems4, dems5, dems6, dems7, dems8, dems9, dems10, dems11, dems12, 
           dems13, dems14, dems15, dems16, dems17, dems18, dems19, dems20, dems21, dems22, dems23]
dem_tw = pd.concat(pdList1)

In [113]:
dem_tw.head()

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:55:03+00:00,1587443101790048258,One more week until Election Day. \n\nLet’s do...,JoeBiden
1,2022-11-01 01:27:00+00:00,1587254848940085253,Democrats will protect Social Security.\nWe’ll...,JoeBiden
2,2022-10-31 22:30:02+00:00,1587210314663215105,"With Election Day right around the corner, I’m...",JoeBiden
3,2022-10-31 20:29:01+00:00,1587179858236305408,I know which side I’m on.\nhttps://t.co/RBiVHJ...,JoeBiden
4,2022-10-31 18:22:05+00:00,1587147915050500103,Make your plan to vote early or on Election Da...,JoeBiden

In [114]:
print(dem_tw.shape)
print(dem_tw.dtypes)
print(dem_tw.isna().sum())

(146664, 4)
Date        datetime64[ns, UTC]
Tweet ID                  int64
Tweet                    object
Username                 object
dtype: object
Date        0
Tweet ID    0
Tweet       0
Username    0
dtype: int64

In [125]:
dem_tw = dem_tw.sort_values(by='Date', ascending = True)
dem_tw = dem_tw.reset_index()
dem_tw = dem_tw.drop(columns=['index'])
dem_tw.Date = pd.to_datetime(dem_tw['Date'])
dem_tw.Date = dem_tw.Date.dt.strftime("%m/%d/%Y")
dem_tw.Date = pd.to_datetime(dem_tw['Date'])
dem_tw['Political_Score'] = 1

In [126]:
dem_tw

,Date,Tweet ID,Tweet,Username,Political_Score
0,2017-01-20,822232466786283521,Let us all stand up for people who deserve to ...,KamalaHarris,1
1,2017-01-20,822240072951013376,A very powerful read about the stories of our ...,PramilaJayapal,1
2,2017-01-20,822242471883243520,"If heaven has a flaw, we're gonna find out soo...",SenSchumer,1
3,2017-01-20,822243371561447424,"Barrett was a brilliant NY beacon, cleaning up...",SenSchumer,1
4,2017-01-20,822248267853352960,Positive conversation with @downtownseattle to...,RepJayapal,1
...,...,...,...,...,...
146659,2022-11-01,1587462060350357504,"This weekend, I am headed to Wisconsin to rall...",BernieSanders,1
146660,2022-11-01,1587462065899425793,RSVP to join us in Eau Claire: https://t.co/UQ...,BernieSanders,1
146661,2022-11-01,1587463481930006530,"If the Republicans control Congress, they’ll t...",PramilaJayapal,1
146662,2022-11-01,1587464191128002560,One week left until one of the most important ...,chuckschumer,1
146663,2022-11-01,1587467028243386374,Election Day is in one week. Visit https://t.c...,TheDemocrats,1

In [127]:
print(dem_tw.shape)
print(dem_tw.dtypes)
print(dem_tw.isna().sum())

(146664, 5)
Date               datetime64[ns]
Tweet ID                    int64
Tweet                      object
Username                   object
Political_Score             int64
dtype: object
Date               0
Tweet ID           0
Tweet              0
Username           0
Political_Score    0
dtype: int64

In [121]:
dem_tw.to_csv('Democratic Party Tweets')

## Webscraping the Republican Party's Tweets

In [30]:
%%time
trumpl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:realdonaldtrump since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    trumpl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop1 = pd.DataFrame(trumpl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop1

CPU times: user 62.7 ms, sys: 5 ms, total: 67.7 ms
Wall time: 532 ms

Empty DataFrame
Columns: [Date, Tweet ID, Tweet, Username]
Index: []

In [31]:
%%time
trumpl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:POTUS45 since:2017-01-20 until:2021-1-19 lang:en').get_items()):
    if i == maxTweets:
        break
    trumpl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop2 = pd.DataFrame(trumpl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop2

CPU times: user 496 ms, sys: 33.3 ms, total: 530 ms
Wall time: 8.95 s

,Date,Tweet ID,Tweet,Username
0,2018-06-01 17:28:09+00:00,1002602715820756993,Record JOBS DAY!! 223K jobs added. Unemploymen...,POTUS45
1,2018-01-31 06:18:32+00:00,958585268252102656,THANK YOU @SteveScalise!\n#SOTU #TeamScalise h...,POTUS45
2,2017-12-01 21:32:52+00:00,936709709641502725,Thank you @SecretaryZinke! https://t.co/r84hnW...,POTUS45
3,2017-11-29 20:15:28+00:00,935965452810977280,Just arrived in Missouri. Heading to St. Charl...,POTUS45
4,2017-11-01 17:04:25+00:00,925770515071021056,Opening remarks at this afternoons @Cabinet me...,POTUS45
...,...,...,...,...
373,2017-01-21 17:18:05+00:00,822855801400414211,"I am honored to serve you, the great American ...",POTUS45
374,2017-01-21 02:25:43+00:00,822631230944460801,"January 20th 2017, will be remembered as the d...",POTUS45
375,2017-01-21 00:47:49+00:00,822606593808277504,Signing documents to allow Mattis and Kelly to...,POTUS45
376,2017-01-20 22:32:17+00:00,822572484742488065,"On behalf of my entire family, THANK YOU! #Ina...",POTUS45
377,2017-01-20 19:11:33+00:00,822521968465416192,#InaugurationDay Speech🇺🇸\nhttps://t.co/2h8yWM...,POTUS45

In [32]:
%%time
trumpl3 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:DonaldJTrumpJr since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    trumpl3.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop3 = pd.DataFrame(trumpl3, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop3

CPU times: user 14.3 s, sys: 597 ms, total: 14.9 s
Wall time: 5min 7s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 14:21:00+00:00,1587449632581472257,The media really think people are stupid enoug...,DonaldJTrumpJr
1,2022-10-31 19:53:34+00:00,1587170938403127296,"Wait, so you’re saying if we actually enforced...",DonaldJTrumpJr
2,2022-10-31 18:52:42+00:00,1587155619613528064,"Meanwhile, over on the taxpayer funded “news” ...",DonaldJTrumpJr
3,2022-10-31 12:39:42+00:00,1587061753434689536,Ban all hammers… https://t.co/VBr8Mfoa85,DonaldJTrumpJr
4,2022-10-31 01:55:31+00:00,1586899639831171072,The internet remains undefeated… Also if you s...,DonaldJTrumpJr
...,...,...,...,...
10148,2017-01-20 13:39:02+00:00,822438289114337281,"On behalf of the entire Trump family, THANK YO...",DonaldJTrumpJr
10149,2017-01-20 13:28:04+00:00,822435528989638656,Wow. Just saw this pic of Kai and her grandpa ...,DonaldJTrumpJr
10150,2017-01-20 03:45:03+00:00,822288805868818433,Couldn't resist breaking out the camera for th...,DonaldJTrumpJr
10151,2017-01-20 01:26:33+00:00,822253951345184770,#Repost @ivankatrump\n・・・\nOn the steps of the...,DonaldJTrumpJr
10152,2017-01-20 01:22:47+00:00,822253003059134465,#Repost foxnews\n・・・\nViewers enjoyed a specta...,DonaldJTrumpJr

In [33]:
%%time
pencel1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:VP45 since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    pencel1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop4 = pd.DataFrame(pencel1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop4

CPU times: user 6.59 s, sys: 327 ms, total: 6.92 s
Wall time: 2min 6s

,Date,Tweet ID,Tweet,Username
0,2021-01-19 20:45:47+00:00,1351631964843999232,Thank you for the privilege of serving as your...,VP45
1,2020-01-01 15:14:45+00:00,1212391720610095106,"In 2017, Speaker Pelosi called President @real...",VP45
2,2019-12-31 23:44:39+00:00,1212157651360079872,A record year for America! The stock market cl...,VP45
3,2019-12-29 20:14:33+00:00,1211380002559799297,Karen and I were shocked by the heinous anti-s...,VP45
4,2019-12-26 20:02:58+00:00,1210289923917529089,"GREAT news: Today, the NASDAQ hit 9,000 for th...",VP45
...,...,...,...,...
5203,2017-01-21 05:22:43+00:00,822675771055542272,Thanks to everyone for a wonderful inaugural e...,VP45
5204,2017-01-20 22:58:50+00:00,822579166176509956,Making the historic journey from US Capitol to...,VP45
5205,2017-01-20 22:37:19+00:00,822573752093380608,"After riding in parade to the @WhiteHouse, we ...",VP45
5206,2017-01-20 20:09:15+00:00,822536488646742019,Inspiring Inaugural Address from President @re...,VP45
5207,2017-01-20 18:05:56+00:00,822505454450470912,It is the honor of my life to serve our countr...,VP45

In [34]:
%%time
pencel2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:Mike_Pence since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    pencel2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop5 = pd.DataFrame(pencel2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop5

CPU times: user 4.52 s, sys: 226 ms, total: 4.75 s
Wall time: 1min 25s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 00:39:47+00:00,1587242968645341184,Mike Pence: Dems Are the Extremists: ‘Abortion...,Mike_Pence
1,2022-10-31 19:56:37+00:00,1587171704794763265,Precious Memories of Trick or Treating in days...,Mike_Pence
2,2022-10-31 17:23:20+00:00,1587133130405994496,Read more in my new book “So Help Me God” out ...,Mike_Pence
3,2022-10-31 15:02:56+00:00,1587097796766621701,“So Help Me God” is the story of my life and I...,Mike_Pence
4,2022-10-31 15:00:56+00:00,1587097295903932419,Looking forward to being in the great state of...,Mike_Pence
...,...,...,...,...
3504,2017-01-20 14:50:42+00:00,822456321433894912,Grateful for the support throughout the transi...,Mike_Pence
3505,2017-01-20 14:17:22+00:00,822447933899599872,We begin this historic and humbling day as we ...,Mike_Pence
3506,2017-01-20 04:21:43+00:00,822298032842637312,Karen and I enjoyed a magical evening at the c...,Mike_Pence
3507,2017-01-20 04:09:05+00:00,822294855611191296,Tomorrow history will be made. Tonight was for...,Mike_Pence
3508,2017-01-20 02:36:58+00:00,822271673206444032,"So very proud of my wife, Karen. She was an am...",Mike_Pence

In [35]:
%%time
cruzl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:tedcruz since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    cruzl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop6 = pd.DataFrame(cruzl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop6

CPU times: user 13.9 s, sys: 561 ms, total: 14.4 s
Wall time: 4min 58s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:33:12+00:00,1587467803124285440,"Skip the corrupt corporate media’s bias, liste...",tedcruz
1,2022-11-01 13:58:44+00:00,1587444027741331462,"Lots of editorializing in this “news”article, ...",tedcruz
2,2022-11-01 12:39:00+00:00,1587423962509627393,Don’t miss the latest episode of #Verdict wher...,tedcruz
3,2022-11-01 03:12:19+00:00,1587281352507916288,"Now Randi is saying, “please don’t blame me fo...",tedcruz
4,2022-11-01 01:53:49+00:00,1587261597738745857,absolutely https://t.co/JWb0dbhgP3,tedcruz
...,...,...,...,...
9839,2017-01-24 19:16:15+00:00,823972699970084864,Disgraceful. https://t.co/DkxJlh8M4Q,tedcruz
9840,2017-01-23 20:05:58+00:00,823622826150293505,"#CruzCrew, TONIGHT at 8 pm CT -- don't miss my...",tedcruz
9841,2017-01-23 14:55:34+00:00,823544711881359361,Join the fight for #TermLimits: https://t.co/I...,tedcruz
9842,2017-01-23 14:55:04+00:00,823544584072466434,Support for term limits cuts across party line...,tedcruz
9843,2017-01-20 18:00:32+00:00,822504097555345409,Scenes from the #Inauguration! https://t.co/ka...,tedcruz

In [36]:
%%time
cruzl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenTedCruz since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    cruzl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop7 = pd.DataFrame(cruzl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop7

CPU times: user 14.2 s, sys: 709 ms, total: 14.9 s
Wall time: 4min 39s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:56:08+00:00,1587473573354119168,President Biden threatening the American energ...,SenTedCruz
1,2022-11-01 14:30:35+00:00,1587452045145116674,RELEASE: Cruz Statement on Oral Arguments in S...,SenTedCruz
2,2022-10-31 22:50:00+00:00,1587215338180997120,One of the scariest things this Halloween:\n\n...,SenTedCruz
3,2022-10-31 21:47:38+00:00,1587199645293363201,We can help expand opportunity for minorities ...,SenTedCruz
4,2022-10-31 21:47:38+00:00,1587199643426988032,"I was encouraged by today’s oral arguments, an...",SenTedCruz
...,...,...,...,...
11076,2017-01-23 20:52:19+00:00,823634489834405888,Joining Mark Levin TONIGHT at 8pm CT on @Levin...,SenTedCruz
11077,2017-01-20 23:51:34+00:00,822592436283277313,Congratulations to Gen. Mattis on his confirma...,SenTedCruz
11078,2017-01-20 18:50:14+00:00,822516604961488896,Scenes from the #Inauguration! https://t.co/a7...,SenTedCruz
11079,2017-01-20 11:53:04+00:00,822411617786855424,Joining @TODAYshow LIVE this morning at 7:40am...,SenTedCruz
11080,2017-01-20 10:32:03+00:00,822391232404004864,Joining @MariaBartiromo @MorningsMaria on @Fox...,SenTedCruz

In [37]:
%%time
rubiol1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:marcorubio since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    rubiol1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop8 = pd.DataFrame(rubiol1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop8

CPU times: user 10.9 s, sys: 538 ms, total: 11.4 s
Wall time: 3min 46s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 23:57:43+00:00,1587232382045851653,In Polk County #Florida lots of enthusiasm for...,marcorubio
1,2022-10-31 21:10:09+00:00,1587190212542795782,The #RedWave2022 is coming to #Florida &amp; i...,marcorubio
2,2022-10-31 17:18:11+00:00,1587131835401781249,We need to make things in America again! \n\n#...,marcorubio
3,2022-10-30 03:40:30+00:00,1586563667927113729,8 days to go https://t.co/20cGof5JrL,marcorubio
4,2022-10-28 17:54:30+00:00,1586053808433823744,It’s disgusting how since Monday some in local...,marcorubio
...,...,...,...,...
8969,2017-01-27 18:32:37+00:00,825048883755638787,Proud to support the thousands who #MarchforLi...,marcorubio
8970,2017-01-25 17:12:06+00:00,824303846423937026,Incredibly proud for my friend @nikkihaley htt...,marcorubio
8971,2017-01-20 12:27:29+00:00,822420281381752832,We also thank @BarackObama @MichelleObama for ...,marcorubio
8972,2017-01-20 12:23:47+00:00,822419351273881605,Today Jeanette &amp; I pray for @realDonaldTru...,marcorubio
8973,2017-01-20 00:33:02+00:00,822240484877799425,@MomToBea @GloryCorinne I have serious concern...,marcorubio

In [38]:
%%time
rubiol2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenRubioPress since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    rubiol2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop9 = pd.DataFrame(rubiol2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop9

CPU times: user 10.2 s, sys: 544 ms, total: 10.8 s
Wall time: 3min 37s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:46:38+00:00,1587471182374240257,"As we begin Military Family Month, Senator Rub...",SenRubioPress
1,2022-11-01 14:37:40+00:00,1587453827770458114,Happy Independence Day to the people of Antigu...,SenRubioPress
2,2022-10-31 19:21:11+00:00,1587162788157333505,What is causing the diesel crisis?\n \nNewswee...,SenRubioPress
3,2022-10-31 17:13:06+00:00,1587130555812007936,The recent sinking of yet another vessel off t...,SenRubioPress
4,2022-10-28 17:16:04+00:00,1586044137169899521,Tibetans &amp; Han Chinese are speaking out ag...,SenRubioPress
...,...,...,...,...
8440,2017-01-24 02:31:07+00:00,823719752145272832,U.S. Senate passes Rubio-Nelson resolution hon...,SenRubioPress
8441,2017-01-24 00:36:25+00:00,823690884751519745,.@RepMikePompeo is extraordinarily qualified t...,SenRubioPress
8442,2017-01-23 23:01:24+00:00,823666973385035778,Got to know Heather Wilson well in 2012. She’s...,SenRubioPress
8443,2017-01-23 21:56:42+00:00,823650694628577280,Congratulations to @AjitPaiFCC on being appoin...,SenRubioPress
8444,2017-01-23 18:53:50+00:00,823604674423128064,US taxpayer $ should not be used to perform or...,SenRubioPress

In [39]:
%%time
mcconnelll1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:LeaderMcConnell since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    mcconnelll1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop10 = pd.DataFrame(mcconnelll1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop10

CPU times: user 3.46 s, sys: 205 ms, total: 3.66 s
Wall time: 1min 11s

,Date,Tweet ID,Tweet,Username
0,2022-10-30 17:15:59+00:00,1586768892311076873,Elaine and I are terribly saddened by the pass...,LeaderMcConnell
1,2022-10-28 15:31:05+00:00,1586017719912210440,Horrified and disgusted by the reports that Pa...,LeaderMcConnell
2,2022-10-13 16:47:45+00:00,1580601193767632903,Democrats have produced staggering 13.5% infla...,LeaderMcConnell
3,2022-10-03 01:49:19+00:00,1576751218810318848,I was deeply saddened to learn this evening th...,LeaderMcConnell
4,2022-09-28 17:40:50+00:00,1575178736785584129,Democrats wanted one-party control of Washingt...,LeaderMcConnell
...,...,...,...,...
3153,2017-01-20 22:53:45+00:00,822577885819047939,James Mattis has been confirmed by the #Senate...,LeaderMcConnell
3154,2017-01-20 17:00:19+00:00,822488942872240128,Congratulations to @realDonaldTrump on becomin...,LeaderMcConnell
3155,2017-01-20 16:54:33+00:00,822487492469391361,Congratulations to @mike_pence on becoming the...,LeaderMcConnell
3156,2017-01-20 16:52:56+00:00,822487085282185218,"1st to be sworn will be our 48th VP, @mike_pen...",LeaderMcConnell
3157,2017-01-20 14:42:20+00:00,822454216174292992,#Inauguration is about to get underway. Thank ...,LeaderMcConnell

In [40]:
%%time
mcconnelll2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:McConnellPress since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    mcconnelll2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop11 = pd.DataFrame(mcconnelll2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop11

CPU times: user 7.11 s, sys: 350 ms, total: 7.46 s
Wall time: 2min 30s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:27:28+00:00,1587466361181245443,.@LeaderMcConnell comments on the tragic death...,McConnellPress
1,2022-10-30 20:37:26+00:00,1586819588448190467,.@LeaderMcConnell: I was heartbroken to learn ...,McConnellPress
2,2022-10-27 18:34:24+00:00,1585701465456316421,.@LeaderMcConnell Directs More Than $21.5 Mill...,McConnellPress
3,2022-10-27 17:37:29+00:00,1585687141132140547,via @MayfieldMSNGR: @LeaderMcConnell announces...,McConnellPress
4,2022-10-27 17:25:07+00:00,1585684029176676354,.@OwensboroTimes reports: @LeaderMcConnell sto...,McConnellPress
...,...,...,...,...
5705,2017-01-24 18:17:36+00:00,823957941543993344,.@SenateMajLdr McConnell statement on @POTUS e...,McConnellPress
5706,2017-01-24 00:00:02+00:00,823681730683006980,"ICYMI - @SenateMajLdr weighs in on #Obamacare,...",McConnellPress
5707,2017-01-23 21:55:08+00:00,823650299760037889,.@SenateMajLdr statement on @POTUS nominee for...,McConnellPress
5708,2017-01-23 20:09:51+00:00,823623803834142721,".@SenateMajLdr: ""Americans are reeling after 8...",McConnellPress
5709,2017-01-23 19:30:04+00:00,823613790281404417,National #SchoolChoice Week is underway w/even...,McConnellPress

In [41]:
%%time
mccarthyl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:GOPLeader since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    mccarthyl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop12 = pd.DataFrame(mccarthyl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop12

CPU times: user 6.27 s, sys: 323 ms, total: 6.59 s
Wall time: 2min 8s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 12:57:58+00:00,1587428736122597377,Only one party says:\n- Only women should comp...,GOPLeader
1,2022-10-31 18:56:00+00:00,1587156449897156610,Republicans have the right plan to make Americ...,GOPLeader
2,2022-10-31 13:55:26+00:00,1587080809898741761,"If you’re tired of runaway inflation,\nIf you’...",GOPLeader
3,2022-10-27 22:50:34+00:00,1585765931845836800,Nearly 4 million illegal immigrants have cross...,GOPLeader
4,2022-10-27 17:06:22+00:00,1585679308626034694,"Winter is coming. And with it, you can expect ...",GOPLeader
...,...,...,...,...
5059,2017-01-25 14:56:05+00:00,824269618621583361,My latest op-ed ➡️ How the House will roll bac...,GOPLeader
5060,2017-01-24 22:07:49+00:00,824015878236897281,The new Republican government has a unity of v...,GOPLeader
5061,2017-01-24 17:17:05+00:00,823942712374067200,My statement on President Trump’s decision to ...,GOPLeader
5062,2017-01-23 18:04:01+00:00,823592134993412098,Our unified Republican government is committed...,GOPLeader
5063,2017-01-20 17:04:27+00:00,822489980589187073,Congratulations to the 45th President of the U...,GOPLeader

In [42]:
%%time
gosarl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepGosar since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    gosarl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop13 = pd.DataFrame(gosarl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop13

CPU times: user 5.99 s, sys: 297 ms, total: 6.29 s
Wall time: 2min 4s

,Date,Tweet ID,Tweet,Username
0,2022-10-31 21:35:27+00:00,1587196579865239552,America First is a winning message.\n\nAmerica...,RepGosar
1,2022-10-31 17:07:44+00:00,1587129206537961474,Elon Musk buying Twitter is a great developmen...,RepGosar
2,2022-10-30 23:45:18+00:00,1586866868719001600,Pray for President Bolsonaro.,RepGosar
3,2022-10-30 22:24:38+00:00,1586846569139159040,Joe Biden must be impeached.,RepGosar
4,2022-10-30 19:49:35+00:00,1586807549038313474,Our southern border is being invaded.\n\nLawbr...,RepGosar
...,...,...,...,...
4711,2017-01-23 05:08:04+00:00,823396860337541120,@CVPDAZ I'm always game for spreading some che...,RepGosar
4712,2017-01-22 13:09:09+00:00,823155542554267653,Congratulations to my friend .@CarlyleBegay! E...,RepGosar
4713,2017-01-20 19:02:38+00:00,822519723451621380,VICTORY! Arizonans Successful in Effort to Blo...,RepGosar
4714,2017-01-20 17:01:28+00:00,822489230366691328,President Donald J. Trump,RepGosar
4715,2017-01-20 16:01:24+00:00,822474116494229504,Excited for the swearing-in of our 45th Presid...,RepGosar

In [43]:
%%time
gosarl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:DrPaulGosar since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    gosarl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop14 = pd.DataFrame(gosarl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop14

CPU times: user 5.74 s, sys: 239 ms, total: 5.98 s
Wall time: 2min 12s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 14:42:36+00:00,1587455068558630914,Great news for Arizona and America—@bgmasters ...,DrPaulGosar
1,2022-10-31 21:40:35+00:00,1587197869613793284,"2. “In 2014, he received just under 70% of the...",DrPaulGosar
2,2022-10-31 21:40:34+00:00,1587197865901842432,“He has become increasingly popular in our con...,DrPaulGosar
3,2022-10-31 02:14:53+00:00,1586904510525427713,Let’s just vote @RealMarkFinchem and we won’t ...,DrPaulGosar
4,2022-10-31 01:56:30+00:00,1586899886452129792,“And stay out!” https://t.co/rTM3aLt0P6 https:...,DrPaulGosar
...,...,...,...,...
3965,2017-06-10 14:03:07+00:00,873541038325084160,I enjoyed my interview with @JamesTHarris. Gre...,DrPaulGosar
3966,2017-06-08 16:28:24+00:00,872852821972070400,Great article on how Congress can restore its ...,DrPaulGosar
3967,2017-06-08 14:46:36+00:00,872827206032130048,A proud history and many reasons to celebrate....,DrPaulGosar
3968,2017-06-08 13:54:11+00:00,872814013142491136,One of my proudest moments was getting the Sou...,DrPaulGosar
3969,2017-06-07 10:24:29+00:00,872398852992753664,"On May 22, 2014 I voted against spying on Amer...",DrPaulGosar

In [44]:
%%time
greenel1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepMTG since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    greenel1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop15 = pd.DataFrame(greenel1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop15

CPU times: user 2.52 s, sys: 142 ms, total: 2.66 s
Wall time: 52 s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:01:18+00:00,1587459772554649601,David Depape was an illegal alien that oversta...,RepMTG
1,2022-10-31 14:04:32+00:00,1587083100961619968,The same mainstream media democrat activists t...,RepMTG
2,2022-10-31 13:38:51+00:00,1587076636477882373,Make America energy independent AGAIN!,RepMTG
3,2022-10-31 13:10:28+00:00,1587069494807203847,No matter the amount of media spin and politic...,RepMTG
4,2022-10-31 13:10:28+00:00,1587069493184008194,No matter the amount of media spin and politic...,RepMTG
...,...,...,...,...
2014,2021-01-04 01:51:28+00:00,1345910688624078851,Day One in the books.\n\nTeam Greene is FIRED ...,RepMTG
2015,2021-01-03 22:20:02+00:00,1345857478576234496,Congress is in session and @SpeakerPelosi chan...,RepMTG
2016,2021-01-03 20:03:29+00:00,1345823114425413634,Just proudly voted to REMOVE @SpeakerPelosi fr...,RepMTG
2017,2021-01-03 17:00:31+00:00,1345777071688183809,I’m here to fight for my children’s future and...,RepMTG
2018,2021-01-03 01:08:01+00:00,1345537364375064577,I’m honored to represent the great people of G...,RepMTG

In [45]:
%%time
paull1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RandPaul since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    paull1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop16 = pd.DataFrame(paull1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop16

CPU times: user 4.79 s, sys: 247 ms, total: 5.04 s
Wall time: 1min 31s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 16:21:59+00:00,1587480078228791301,Huge crowd in Elizabethtown ready for a red wa...,RandPaul
1,2022-11-01 15:44:06+00:00,1587470546513846273,We dehumanize everyone in politics. We should ...,RandPaul
2,2022-11-01 15:12:22+00:00,1587462561376747521,Thank you Georgetown for coming out to rally f...,RandPaul
3,2022-11-01 14:15:59+00:00,1587448369919795205,What a great way to start the day bright and e...,RandPaul
4,2022-11-01 13:17:18+00:00,1587433603256156165,I'll always be a fighter for the truth and for...,RandPaul
...,...,...,...,...
3848,2017-01-27 17:02:25+00:00,825026185147080704,Thousands #MarchforLife to give voice to those...,RandPaul
3849,2017-01-24 00:25:19+00:00,823688092028719112,Protecting the entire Bill of Rights is one of...,RandPaul
3850,2017-01-24 00:16:21+00:00,823685837476995072,Rand Paul: Why I voted against the new CIA dir...,RandPaul
3851,2017-01-21 21:04:29+00:00,822912777815752706,We had a great time with @ericbolling and @wil...,RandPaul
3852,2017-01-20 13:48:59+00:00,822440790182006786,Joining @Morning_Joe on @MSNBC in a few minute...,RandPaul

In [46]:
%%time
cottonl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenTomCotton since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    cottonl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop17 = pd.DataFrame(cottonl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop17

CPU times: user 5.62 s, sys: 347 ms, total: 5.97 s
Wall time: 1min 58s

,Date,Tweet ID,Tweet,Username
0,2022-10-27 13:43:02+00:00,1585628138670903297,Reminder: Washington D.C. wants to let illegal...,SenTomCotton
1,2022-10-25 16:34:20+00:00,1584946471295930368,Thank you to the law enforcement and healthcar...,SenTomCotton
2,2022-10-21 18:47:49+00:00,1583530511137243138,“Cotton was years ahead of what’s now the domi...,SenTomCotton
3,2022-10-19 18:16:27+00:00,1582797842946887681,Allowing illegal immigrants to vote is an insu...,SenTomCotton
4,2022-10-19 13:53:10+00:00,1582731585513668608,Washington D.C. just moved to let illegal alie...,SenTomCotton
...,...,...,...,...
4948,2017-01-20 15:43:28+00:00,822469600730288129,This morning I joined @Morning_Joe to discuss ...,SenTomCotton
4949,2017-01-20 14:27:56+00:00,822450593910419457,Today we will witness history and a hallmark o...,SenTomCotton
4950,2017-01-20 12:39:50+00:00,822423390963240960,Talking #InaugurationDay with @hughhewitt and ...,SenTomCotton
4951,2017-01-20 11:59:34+00:00,822413256690200577,Joining the @hughhewitt radio show shortly. Tu...,SenTomCotton
4952,2017-01-20 11:13:51+00:00,822401752561582080,Joining @Morning_Joe shortly. Tune in!,SenTomCotton

In [47]:
%%time
cottonl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:TomCottonAR since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    cottonl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop18 = pd.DataFrame(cottonl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop18

CPU times: user 5.18 s, sys: 265 ms, total: 5.45 s
Wall time: 1min 45s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 14:58:25+00:00,1587459047359479809,The Biden Admin is STILL trying to force toddl...,TomCottonAR
1,2022-11-01 14:20:13+00:00,1587449433972776962,Great to be on @foxandfriends to talk about ho...,TomCottonAR
2,2022-11-01 12:59:15+00:00,1587429058807201794,Thanks for having me on! \n\nCheck out the ins...,TomCottonAR
3,2022-11-01 12:49:39+00:00,1587426644960198658,It's out! \n\nIf you want to know why Biden we...,TomCottonAR
4,2022-11-01 00:53:30+00:00,1587246420045824000,The “success” of a record spike in the murder ...,TomCottonAR
...,...,...,...,...
3919,2017-01-26 17:46:06+00:00,824674790153875456,Workers support @realDonaldTrump no matter wha...,TomCottonAR
3920,2017-01-24 12:56:46+00:00,823877200852160513,Whether you're a new cabinet secretary or a ne...,TomCottonAR
3921,2017-01-24 02:42:23+00:00,823722586186063872,A great night for America &amp; the CIA https:...,TomCottonAR
3922,2017-01-21 20:44:57+00:00,822907858580893696,Strong statement of support by @realDonaldTrum...,TomCottonAR
3923,2017-01-20 03:59:40+00:00,822292484936110081,"Donald Trump &amp; Andrew Jackson, biggest win...",TomCottonAR

In [48]:
%%time
scottl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:SenRickScott since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    scottl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop19 = pd.DataFrame(scottl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop19

CPU times: user 14.4 s, sys: 704 ms, total: 15.1 s
Wall time: 5min 2s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 16:32:26+00:00,1587482708128694272,"📰 IN THE NEWS: Rick Scott, Marco Rubio urge NO...",SenRickScott
1,2022-11-01 15:01:47+00:00,1587459896349495296,"Happy Birthday, @MaElviraSalazar! \n\nThanks f...",SenRickScott
2,2022-11-01 13:20:00+00:00,1587434280757514241,#Bidenflation is an attack on Florida's senior...,SenRickScott
3,2022-11-01 00:29:53+00:00,1587240473919365122,This is an evil regime that is scared to death...,SenRickScott
4,2022-10-31 20:57:02+00:00,1587186909788479488,To favor or discriminate against students base...,SenRickScott
...,...,...,...,...
10934,2017-01-20 16:54:42+00:00,822487529941254145,At the inauguration with @FLAnnScott about to ...,SenRickScott
10935,2017-01-20 15:45:01+00:00,822469991811321858,The @realDonaldTrump and @mike_pence administr...,SenRickScott
10936,2017-01-20 15:33:40+00:00,822467136367063046,"More than 237,000 new jobs were created for fa...",SenRickScott
10937,2017-01-20 15:19:42+00:00,822463619501883395,"Today, we proudly welcome a new president @rea...",SenRickScott
10938,2017-01-20 14:43:31+00:00,822454515584684032,I’m excited to watch my friend @realDonaldTrum...,SenRickScott

In [49]:
%%time
scottl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:ScottforFlorida since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    scottl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop20 = pd.DataFrame(scottl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop20

CPU times: user 2.9 s, sys: 156 ms, total: 3.05 s
Wall time: 57.5 s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 13:58:06+00:00,1587443868131381249,"Welcome to Florida, @JoeBiden.\n\nLook forward...",ScottforFlorida
1,2022-11-01 12:02:40+00:00,1587414820890066944,📻 Joining @NHTodayShow with Christopher Ryan a...,ScottforFlorida
2,2022-10-31 23:36:53+00:00,1587227137563557888,".@JoeBiden cheated on his own taxes, taking ev...",ScottforFlorida
3,2022-10-31 21:17:53+00:00,1587192155839275009,Heard @JoeBiden was making a visit to Florida ...,ScottforFlorida
4,2022-10-31 11:53:16+00:00,1587050067336347649,Starting the morning off right at Simply Delic...,ScottforFlorida
...,...,...,...,...
2213,2017-02-02 17:23:58+00:00,827205937861627904,Creating more jobs in Florida is the most impo...,ScottforFlorida
2214,2017-01-27 18:15:19+00:00,825044530865065984,"Success is spending less on welfare, less on f...",ScottforFlorida
2215,2017-01-25 15:24:28+00:00,824276759852027905,Cutting taxes helps generate economic activity...,ScottforFlorida
2216,2017-01-23 23:16:01+00:00,823670654071410689,Results from our survey: As has been the case ...,ScottforFlorida
2217,2017-01-23 21:55:38+00:00,823650424435646467,We just completed a statewide survey wanted to...,ScottforFlorida

In [50]:
%%time
jordanl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:Jim_Jordan since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    jordanl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop21 = pd.DataFrame(jordanl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop21

CPU times: user 4.53 s, sys: 247 ms, total: 4.77 s
Wall time: 1min 25s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 16:16:17+00:00,1587478645676949504,We going to make sure that the #SCOTUS decisio...,Jim_Jordan
1,2022-11-01 15:14:06+00:00,1587462996909084682,Make America Safe Again.,Jim_Jordan
2,2022-11-01 13:04:46+00:00,1587430446505287680,In America:\n\n-The First Amendment should be ...,Jim_Jordan
3,2022-11-01 01:40:02+00:00,1587258128978018308,POLICE to AMERICA:\n\n“We cannot keep you safe...,Jim_Jordan
4,2022-10-31 22:08:48+00:00,1587204971933696000,The #COVID vaccine mandate for our military ha...,Jim_Jordan
...,...,...,...,...
3679,2017-01-27 17:41:32+00:00,825036030562611201,Thanks @SenatorRisch for your efforts!,Jim_Jordan
3680,2017-01-27 16:40:35+00:00,825020692840091648,"Any #Ohio #MarchForLife attendees, join my sta...",Jim_Jordan
3681,2017-01-25 21:19:19+00:00,824366059234934786,These actions will also benefit millions who w...,Jim_Jordan
3682,2017-01-25 21:17:46+00:00,824365670137729024,.@POTUS Trump actions today are the first step...,Jim_Jordan
3683,2017-01-20 18:13:34+00:00,822507374367952896,Thoughts and prayers with West Liberty High Sc...,Jim_Jordan

In [51]:
%%time
boebertl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:laurenboebert since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    boebertl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop22 = pd.DataFrame(boebertl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop22

CPU times: user 7.01 s, sys: 432 ms, total: 7.44 s
Wall time: 2min 24s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 16:51:11+00:00,1587487427681214467,.@JoeRogan gets it. Every horrible policy prop...,laurenboebert
1,2022-11-01 15:16:26+00:00,1587463582563844096,While the Left wants to make this election abo...,laurenboebert
2,2022-11-01 13:30:52+00:00,1587437017415155712,"One week, America. \n\nLet’s finish strong!",laurenboebert
3,2022-11-01 11:52:02+00:00,1587412144894640128,Joe Biden is now threatening oil companies wit...,laurenboebert
4,2022-11-01 01:55:50+00:00,1587262106864218112,@mattgaetz @RepMTG @Jim_Jordan Winning!,laurenboebert
...,...,...,...,...
6165,2019-12-09 17:31:27+00:00,1204091198572384270,It is for FREEDOM! There is a battle for the h...,laurenboebert
6166,2019-12-09 13:09:05+00:00,1204025174212915204,Colorado’s 3rd Congressional District. You can...,laurenboebert
6167,2019-12-09 12:51:11+00:00,1204020666166497282,Join our movement! Take action with us at http...,laurenboebert
6168,2019-12-08 22:10:49+00:00,1203799117945810952,There’s a battle for the heart and soul of our...,laurenboebert
6169,2019-12-08 21:57:00+00:00,1203795639945121793,Thank you @evanmtodd #ColumbineSurvivor https:...,laurenboebert

In [52]:
%%time
boebertl2 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:RepBoebert since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    boebertl2.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop23 = pd.DataFrame(boebertl2, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop23

CPU times: user 1.67 s, sys: 101 ms, total: 1.77 s
Wall time: 31.5 s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 16:37:28+00:00,1587483977794846726,The border crisis created the fentanyl epidemi...,RepBoebert
1,2022-11-01 15:30:50+00:00,1587467205280759809,Read more here to learn about the important wo...,RepBoebert
2,2022-11-01 14:08:13+00:00,1587446416712126464,"For two years, I have been working on the issu...",RepBoebert
3,2022-10-31 21:57:19+00:00,1587202079256453122,My office has hosted hundreds of Mobile Office...,RepBoebert
4,2022-10-31 19:41:10+00:00,1587167818277158912,Local veterans had a dedication for the recent...,RepBoebert
...,...,...,...,...
1326,2021-01-04 01:23:03+00:00,1345903535163138048,I’m proud to take the oath of office to repres...,RepBoebert
1327,2021-01-04 00:37:46+00:00,1345892141449543681,The Second Amendment is more important now tha...,RepBoebert
1328,2021-01-03 19:09:52+00:00,1345809620560994306,I’m on my way to cast one of my first votes in...,RepBoebert
1329,2021-01-03 17:30:54+00:00,1345784718177038337,The fight for liberty and freedom never stops....,RepBoebert
1330,2021-01-03 14:20:39+00:00,1345736838779179010,"Today, I will proudly take the oath of office ...",RepBoebert

In [53]:
%%time
gopl1 = []
maxTweets = 100000
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:GOP since:2017-01-20 lang:en').get_items()):
    if i == maxTweets:
        break
    gopl1.append([tweet.date, tweet.id, tweet.content, tweet.user.username])
gop24 = pd.DataFrame(gopl1, columns=['Date', 'Tweet ID', 'Tweet', 'Username'])

gop24

CPU times: user 22.7 s, sys: 1.3 s, total: 24 s
Wall time: 7min 48s

,Date,Tweet ID,Tweet,Username
0,2022-11-01 15:04:01+00:00,1587460458608459789,Awesome work @NJGOPField &amp; @NJGOP!\n\nKeep...,GOP
1,2022-11-01 13:49:00+00:00,1587441578779385857,7️⃣7️⃣7️⃣7️⃣7️⃣7️⃣7️⃣\n\n1 week until election...,GOP
2,2022-11-01 11:11:00+00:00,1587401816647426049,.@GOPChairwoman’s advice 7 days before the ele...,GOP
3,2022-11-01 09:25:00+00:00,1587375142824468480,Voters across the country are tired of Democra...,GOP
4,2022-11-01 07:34:00+00:00,1587347207598006274,The result of a Democrat majority in DC👇\n\n🚨7...,GOP
...,...,...,...,...
19142,2017-01-20 23:28:44+00:00,822586691995181058,Congratulations to our newest Secretary of Hom...,GOP
19143,2017-01-20 22:36:08+00:00,822573453110874113,Congratulations to our newest Secretary of Def...,GOP
19144,2017-01-20 17:00:37+00:00,822489015886741504,The 45th President of the United States of Ame...,GOP
19145,2017-01-20 16:54:43+00:00,822487532864737286,The 48th Vice President of the United States o...,GOP
19146,2017-01-20 14:12:02+00:00,822446591399395328,Today is the day we make history. Let's #MakeA...,GOP

## Creating the Republican Party Tweet Dataframe

In [133]:
pdList2 = [gop1, gop2, gop3, gop4, gop5, gop6, gop7, gop8, gop9, gop10, gop11, gop12, 
           gop13, gop14, gop15, gop16, gop17, gop18, gop19, gop20, gop21, gop22, gop23, gop24]
gop_tw = pd.concat(pdList2)

In [134]:
gop_tw.head()

,Date,Tweet ID,Tweet,Username
0,2018-06-01 17:28:09+00:00,1002602715820756993,Record JOBS DAY!! 223K jobs added. Unemploymen...,POTUS45
1,2018-01-31 06:18:32+00:00,958585268252102656,THANK YOU @SteveScalise!\n#SOTU #TeamScalise h...,POTUS45
2,2017-12-01 21:32:52+00:00,936709709641502725,Thank you @SecretaryZinke! https://t.co/r84hnW...,POTUS45
3,2017-11-29 20:15:28+00:00,935965452810977280,Just arrived in Missouri. Heading to St. Charl...,POTUS45
4,2017-11-01 17:04:25+00:00,925770515071021056,Opening remarks at this afternoons @Cabinet me...,POTUS45

In [135]:
print(gop_tw.shape)
print(gop_tw.dtypes)
print(gop_tw.isna().sum())

(138448, 4)
Date        datetime64[ns, UTC]
Tweet ID                 object
Tweet                    object
Username                 object
dtype: object
Date        0
Tweet ID    0
Tweet       0
Username    0
dtype: int64

In [136]:
gop_tw['Tweet ID'] = gop_tw['Tweet ID'].astype(int)
gop_tw = gop_tw.sort_values(by='Date', ascending = True)
gop_tw = gop_tw.reset_index()
gop_tw = gop_tw.drop(columns=['index'])
gop_tw.Date = pd.to_datetime(gop_tw['Date'])
gop_tw.Date = gop_tw.Date.dt.strftime("%m/%d/%Y")
gop_tw.Date = pd.to_datetime(gop_tw['Date'])
gop_tw['Political_Score'] = 0

In [137]:
gop_tw

,Date,Tweet ID,Tweet,Username,Political_Score
0,2017-01-20,822240484877799425,@MomToBea @GloryCorinne I have serious concern...,marcorubio,0
1,2017-01-20,822253003059134465,#Repost foxnews\n・・・\nViewers enjoyed a specta...,DonaldJTrumpJr,0
2,2017-01-20,822253951345184770,#Repost @ivankatrump\n・・・\nOn the steps of the...,DonaldJTrumpJr,0
3,2017-01-20,822271673206444032,"So very proud of my wife, Karen. She was an am...",Mike_Pence,0
4,2017-01-20,822288805868818433,Couldn't resist breaking out the camera for th...,DonaldJTrumpJr,0
...,...,...,...,...,...
138443,2022-11-01,1587478645676949504,We going to make sure that the #SCOTUS decisio...,Jim_Jordan,0
138444,2022-11-01,1587480078228791301,Huge crowd in Elizabethtown ready for a red wa...,RandPaul,0
138445,2022-11-01,1587482708128694272,"📰 IN THE NEWS: Rick Scott, Marco Rubio urge NO...",SenRickScott,0
138446,2022-11-01,1587483977794846726,The border crisis created the fentanyl epidemi...,RepBoebert,0
138447,2022-11-01,1587487427681214467,.@JoeRogan gets it. Every horrible policy prop...,laurenboebert,0

In [138]:
print(gop_tw.shape)
print(gop_tw.dtypes)
print(gop_tw.isna().sum())

(138448, 5)
Date               datetime64[ns]
Tweet ID                    int64
Tweet                      object
Username                   object
Political_Score             int64
dtype: object
Date               0
Tweet ID           0
Tweet              0
Username           0
Political_Score    0
dtype: int64

In [139]:
gop_tw.to_csv('Republican Party Tweets')

## Creating our Dataframe

In [142]:
dfs = [dem_tw, gop_tw]
df = pd.concat(dfs)
df

,Date,Tweet ID,Tweet,Username,Political_Score
0,2017-01-20,822232466786283521,Let us all stand up for people who deserve to ...,KamalaHarris,1
1,2017-01-20,822240072951013376,A very powerful read about the stories of our ...,PramilaJayapal,1
2,2017-01-20,822242471883243520,"If heaven has a flaw, we're gonna find out soo...",SenSchumer,1
3,2017-01-20,822243371561447424,"Barrett was a brilliant NY beacon, cleaning up...",SenSchumer,1
4,2017-01-20,822248267853352960,Positive conversation with @downtownseattle to...,RepJayapal,1
...,...,...,...,...,...
138443,2022-11-01,1587478645676949504,We going to make sure that the #SCOTUS decisio...,Jim_Jordan,0
138444,2022-11-01,1587480078228791301,Huge crowd in Elizabethtown ready for a red wa...,RandPaul,0
138445,2022-11-01,1587482708128694272,"📰 IN THE NEWS: Rick Scott, Marco Rubio urge NO...",SenRickScott,0
138446,2022-11-01,1587483977794846726,The border crisis created the fentanyl epidemi...,RepBoebert,0
138447,2022-11-01,1587487427681214467,.@JoeRogan gets it. Every horrible policy prop...,laurenboebert,0

In [143]:
print(df.shape)
print(df.dtypes)
print(df.isna().sum())

(285112, 5)
Date               datetime64[ns]
Tweet ID                    int64
Tweet                      object
Username                   object
Political_Score             int64
dtype: object
Date               0
Tweet ID           0
Tweet              0
Username           0
Political_Score    0
dtype: int64

In [144]:
df = df.sort_values(by='Date', ascending = True)
df = df.reset_index()
df = df.drop(columns=['index'])
df.Date = pd.to_datetime(df['Date'])

In [145]:
print(df.shape)
print(df.dtypes)
print(df.isna().sum())

(285112, 5)
Date               datetime64[ns]
Tweet ID                    int64
Tweet                      object
Username                   object
Political_Score             int64
dtype: object
Date               0
Tweet ID           0
Tweet              0
Username           0
Political_Score    0
dtype: int64

In [146]:
df

,Date,Tweet ID,Tweet,Username,Political_Score
0,2017-01-20,822232466786283521,Let us all stand up for people who deserve to ...,KamalaHarris,1
1,2017-01-20,822487532864737286,The 48th Vice President of the United States o...,GOP,0
2,2017-01-20,822488942872240128,Congratulations to @realDonaldTrump on becomin...,LeaderMcConnell,0
3,2017-01-20,822489015886741504,The 45th President of the United States of Ame...,GOP,0
4,2017-01-20,822489230366691328,President Donald J. Trump,RepGosar,0
...,...,...,...,...,...
285107,2022-11-01,1587235471188324353,“True but bad for Democrats”\n\nThat’s Big Tec...,tedcruz,0
285108,2022-11-01,1587467028243386374,Election Day is in one week. Visit https://t.c...,TheDemocrats,1
285109,2022-11-01,1587483977794846726,The border crisis created the fentanyl epidemi...,RepBoebert,0
285110,2022-11-01,1587257366055211009,There is a clear choice in Arizona: @bgmasters...,GOP,0
285111,2022-11-01,1587487427681214467,.@JoeRogan gets it. Every horrible policy prop...,laurenboebert,0

In [147]:
df.to_csv('Capstone Project Dataframe')